import { QUIZ_QUESTIONS, MYTHS, ELECTION_PHASES, BOOTH_STEPS, SUGGESTED_QUESTIONS, DEMO_CHAT } from './componentData.js';

// Define all static UI strings used in the app here.
// These will be translated in one batch when the language changes.
const STATIC_STRINGS = [
  "VoteWise",
  "First Time Voter? Start Here →",
  "First Timer Mode ON — Everything explained simply ✓",
  "Beginner Friendly",
  "Translation temporarily unavailable. Showing English content.",
  "",
  "Exit First Timer Mode",
  "\\n",
  "VoteWise Assistant",
  "Powered by Gemini AI",
  "Language changed to",
  "Hello! I'm VoteWise, your AI election assistant. How can I help you understand the voting process today?",
  "Demo Mode is active. To get real AI responses from Gemini, disable Demo Mode and ensure your API key is set in the .env file.",
  "Couldn't connect to the assistant. Please try again.",
  "Type your question...",
  "Please enter a valid age.",
  "You need to be a citizen of India to vote here.",
  "You are not yet eligible because you are not an Indian citizen.",
  "Learn about overall eligibility here",
  "People declared medically unsound by a judge cannot vote.",
  "Individuals declared to be of unsound mind by a competent court cannot be enrolled.",
  "You have to wait! You can vote around {year} when you turn 18.",
  "You are not yet eligible because you are under 18. You will be eligible around {year}.",
  "Check young voter resources",
  "You are eligible to vote!",
  "Voter Eligibility Checker",
  "How old are you?",
  "Are you a citizen of the country?",
  "Yes",
  "No",
  "Have you been declared of unsound mind by a competent court?",
  "Check Eligibility",
  "Awesome! You are ready to vote.",
  "Get your voter card (EPIC) now! →",
  "Register using Form 6 (Voter Registration) →",
  "e.g. 20",
  "Myth",
  "Fact",
  "Learn more on VoteWise PWA",
  "Myth vs Fact",
  "Card {current} of {total}",
  "Copied!",
  "Share this fact",
  "Previous card",
  "Next card",
  "Share this fact via clipboard",
  "Inside the Polling Booth",
  "What exactly happens when you walk in? Follow the 8 steps.",
  "Step",
  "Understanding VVPAT",
  "VVPAT",
  "Thermal Printer Unit",
  "Transparent Window",
  "Sealed Drop Box",
  "Voter Verifiable Paper Audit Trail",
  "Where you see the printed slip for exactly 7 seconds.",
  "Instantly prints the slip based on your EVM selection.",
  "Drop Box",
  "The slip automatically cuts and falls into this sealed box.",
  "EVM Connection Port",
  "Connects securely to the main voting machine.",
  "The VVPAT was introduced in Indian elections in 2013. As of 2019, every polling booth in India uses a VVPAT.",
  "The Ink That Protects Democracy",
  "What it is",
  "A purple-black ink made from Silver Nitrate, applied using a marked pen.",
  "Which finger",
  "Left hand index finger, on the nail and skin just below it.",
  "How long it lasts",
  "2 to 3 weeks — it cannot be removed by washing, scrubbing, or chemicals.",
  "Prevents a person from voting more than once at any booth in the country.",
  "Fun Fact",
  "Why it's used",
  "India's indelible ink is manufactured exclusively by Mysore Paints and Varnish Ltd., a government company established in 1937. It is exported to over 25 countries for their elections!",
  "Test Your Election Knowledge",
  "Take our 10-question quiz to see how well you understand voting rights, processes, and rules.",
  "Start Demo Quiz",
  "Start Quiz",
  "Score",
  "Streak",
  "What you learned",
  "The Election Commission administers elections.",
  "Voting age is 18 years old.",
  "NOTA lets you express dissatisfaction.",
  "EVMs and VVPATs ensure voting accuracy and transparency.",
  "Share Score",
  "Retake Quiz",
  "Question",
  "of",
  "Streak!",
  "Correct!",
  "Incorrect.",
  "Check Answer",
  "Next Question",
  "View Results",
  "Excellent Citizen!",
  "Good Job!",
  "Keep Learning!",
  "You've completed the VoteWise Quiz. The electoral process relies on informed citizens like you.",
  "Election Lifecycle",
  "Current Phase:",
  "Learn",
  "Ask",
  "Quiz",
  "Search languages...",
  "Demo Mode Active",
  "Enable Demo Mode",
  "Ask me anything about the election process, eligibility, or procedures!",
  "Learn About the Election Process",
  "Understand how elections work, key timelines, and step-by-step voting procedures.",
  "First Timer Mode ON ✓",
  "Turns on simpler language!"
];

export const UI_STRINGS = Array.from(new Set([
  ...STATIC_STRINGS,
  ...QUIZ_QUESTIONS.map(q => q.question),
  ...QUIZ_QUESTIONS.flatMap(q => q.options),
  ...QUIZ_QUESTIONS.map(q => q.explanation),
  ...ELECTION_PHASES.map(p => p.title),
  ...ELECTION_PHASES.map(p => p.description),
  ...ELECTION_PHASES.map(p => p.simpleDescription),
  ...MYTHS.map(m => m.myth),
  ...MYTHS.map(m => m.fact),
  ...BOOTH_STEPS.map(s => s.title),
  ...BOOTH_STEPS.map(s => s.text),
  ...SUGGESTED_QUESTIONS,
  ...DEMO_CHAT.map(m => m.content)
].filter(Boolean)));
